### ISSUE TITLE
Improve code generated to avoid unused local assignments

### ISSUE THREAD

**Issue by apupier** [prometheus/client_model#20]
you can see a PR for all unused local assignments https://github.com/openshift/origin/pull/17409 (the example has been copied from this one)

**Comment by beorn7** [comment]
Since this is generated code, we cannot really fix the generated code but needed to fix the code generator.
On the other hand, I'd assume that unused local variable assignments are removed by the compiler anyway.

If you feel this should be fixed, I'm afraid you have to bring that to the maintainers of the Java protobuf compiler.
