### ISSUE TITLE
Publishing a new release

### ISSUE THREAD

**Issue by leoromanovsky** [prometheus/client_model#35]
Hello, are you planning on publishing a new artifact. The one in the "Releases" tab is very out of date and no longer compiles with latest version of Prometheus.

**Comment by beorn7** [comment]
We don't really do releases on this repo, and we don't plan any. These repo is mostly obsolete because most parts of the ecosystem don't use these protobuffers anymore (or never had). A notable exception is prometheus/client_golang, but even there, the use of these protobufs will disappear in v2.

The tagged release doesn't really have a semver compliant tag and was (IIRC) just done to try something out with maven or something.

In general, if you are keen on using the protobufs, it should be fine to use the latest commit.

What kind of compilation problems do you have?

**Comment by leoromanovsky** [comment]
Thank you for replying and you nailed it.

The build tool I use at work, Bazel, out of the box uses semver releases to resolve the dependency from `client_golang`. The single release of `client_model` has code references to modules in `code.google.com` domain which no longer exist, and wouldn't compile.

I'm not blocked as I updated my package building to pull in the latest commit from this repo. Great to hear about the upcoming v2 coming out and resolving this.
