### ISSUE TITLE
upgrade protobuf-java@2.5.0 to 3.4.0

### ISSUE THREAD

**Issue by kmova** [prometheus/client_model#36]
Snyk vulnerability scanner reported that the protobuf needs to be updated. https://github.com/openebs/node-disk-manager/pull/348

Can I go ahead with raising a PR to upgrade the version here: https://github.com/prometheus/client_model/blob/master/pom.xml#L47

**Comment by beorn7** [comment]
The Prometheus project doesn't use the Java protobufs anymore. This repo is essentially only here because protobufs are still used in the Go client, and even that usage will go away eventually.

If you know active users of the Java protobufs (including yourself), we should consider the upgrade (if it is easy).

**Comment by kmova** [comment]
Thanks @beorn7 for quick response. OpenEBS does not use the Java protobufs. This got flagged via the go vendored project.

**Comment by beorn7** [comment]
Java support is gone, so this is obsolete.
